plugins { 
    id 'java-library'; 
    id 'maven-publish';
}

group = 'com.github.sep-es-br'
version = '1.0.0'
sourceCompatibility = '11'
targetCompatibility = '11'

repositories { 
    mavenCentral() 
}

compileJava {
    options.compilerArgs << '-parameters'
}

publishing { 
    publications { 
        mavenJava(MavenPublication) { 
            artifactId = 'openpmo-plugin-sigef-interface'; 
            from components.java 
        } 
    } 
}

dependencies {
    
    api 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.22.1';
}